name: Build

on:
  push:

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Apt Repository
        run: sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: Unit Tests Results
          files: |
            build/test-results/test/*.xml
          comment_mode: off

      - name: Run Integration Tests
        run: ./gradlew testIntegration

      - name: Publish Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: Integration Tests Results
          files: |
            build/test-results/testIntegration/*.xml
          comment_mode: off

      - name: Run Component Tests
        run: ./gradlew testComponent

      - name: Publish Component Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: Component Tests Results
          files: |
            build/test-results/testComponent/*.xml
          comment_mode: off

      - name: Run Architecture Tests
        run: ./gradlew testArchitecture

      - name: Publish Architecture Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: Architecture Tests Results
          files: |
            build/test-results/testArchitecture/*.xml
          comment_mode: off

      - name: Publish All Tests Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: All Tests Results
          files: |
            build/test-results/**/*.xml
          comment_mode: off

      - name: Run Coverage Report
        run: ./gradlew jacocoTestReport

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage_report_name: Coverage Results
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false

      - name: Add Jacocoo report to workflow run summary
        run: |
           echo "" >> $GITHUB_STEP_SUMMARY
           echo "## JaCoCo Code Coverage Report" >> $GITHUB_STEP_SUMMARY
           echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
           echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
           echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
           echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
           echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
           echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      - name: Upload Code Coverage Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-markdown
          path: '*/coverage-results.md'
          retention-days: 1

      - name: Run Mutation Tests
        run: ./gradlew pitest

      - name: Publish Pitest Report
        uses: Bonajo/pitest-report-action@v1.0.0
        with:
          file: build/reports/pitest/mutations.xml

      - name: Run Detekt Linting
        run: ./gradlew detekt

      - name: Publish Detekt Linting Results
        uses: MeilCli/android-lint-statistics@v2
        with:
          lint_xml_file_path: 'build/reports/detekt/**.xml'